[package]
name = "argan"
version = "0.0.0"
edition = "2021"
description = "Experiment."
license = "MIT OR Apache-2.0"
authors = ["Shohruh Adham <shohruh.adham@gmail.com>"]

[dependencies]
cookie = { version = "0.18.0", features = ["percent-encode"] }
http = "1.0.0"
http-body-util = "0.1.0"
hyper = { version = "1.0.1", features = ["full"] }
mime = "0.3.17"
percent-encoding = "2.3.0"
pin-project-lite = "0.2.13"
regex = "1.9.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
serde_urlencoded = "0.7.1"
tower-layer = "0.3.2"

[dev-dependencies]
tokio = { version = "1.28.1", features = ["rt-multi-thread", "macros", "test-util", "parking_lot"] }
criterion = { version = "0.5.1", features = ["async_tokio"] }

[[bench]]
name = "request_routing"
harness = false

