[package]
name = "argan"
version = "0.0.0"
edition = "2021"
description = "Experiment."
license = "MIT OR Apache-2.0"
authors = ["Shohruh Adham <shohruh.adham@gmail.com>"]

[dependencies]
base64 = "0.22.0"
biscotti = "0.2.1"
bytes = "1.5.0"
cookie = { version = "0.18.0", features = ["percent-encode", "secure"] }
fastwebsockets = { version = "0.7.1", features = ["upgrade"] }
flate2 = "1.0.28"
futures-util = "0.3.30"
http = "1.0.0"
http-body-util = "0.1.0"
httparse = "1.8.0"
httpdate = "1.0.3"
hyper = { version = "1.2.0", features = ["full"] }
hyper-util = { version = "0.1.3", features = ["tokio"] }
mime = "0.3.17"
mime_guess = "2.0.4"
multer = { version = "3.0.0", features = ["json"] }
percent-encoding = "2.3.0"
pin-project = "1.1.3"
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
regex = "1.9.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
serde_urlencoded = "0.7.1"
sha1 = "0.10.6"
thiserror = "1.0.56"
tokio = { version = "1.28.1", features = ["rt-multi-thread"] }
tower-layer = "0.3.2"
tower-service = "0.3.2"

[dev-dependencies]
tokio = { version = "1.28.1", features = ["rt-multi-thread", "macros", "test-util", "parking_lot"] }
criterion = { version = "0.5.1", features = ["async_tokio"] }

[[bench]]
name = "request_routing"
harness = false

