[package]
name = "argan"
version = "0.0.0"
edition = "2021"
description = "Experiment."
license = "MIT OR Apache-2.0"
authors = ["Shohruh Adham <shohruh.adham@gmail.com>"]

[dependencies]
either = "1.8.1"
http-body-util = "0.1.0-rc.2"
hyper = { version = "1.0.0-rc.3", features = ["full"] }
