[package]
name = "argan"
version = "0.0.0"
edition = "2021"
description = "Experiment."
license = "MIT OR Apache-2.0"
authors = ["Shohruh Adham <shohruh.adham@gmail.com>"]

[dependencies]
either = "1.8.1"
http = "0.2.9"
http-body-util = "0.1.0-rc.3"
hyper = { version = "1.0.0-rc.4", features = ["full"] }
pin-project = "1.1.2"
regex = "1.9.1"
