[workspace]

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
bytes = "1"
http = "1"
http-body = "1"
http-body-util = "0.1"
futures-util = "0.3"
thiserror = "1"
mime = "0.3"

[workspace.lints.rust]
unsafe_code = "forbid"

[package]
name = "argan"
version = "0.0.0"
description = "Experiment."
authors = ["Shohruh Adham <shohruh.adham@gmail.com>"]
license.workspace = true
edition.workspace = true

[dependencies]
argan-core = { version = "0.0.0", path = "argan-core" }
bytes = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
futures-util = { workspace = true }
thiserror = {workspace = true}
mime = { workspace = true }
base64 = "0.22.0"
cookie = { version = "0.18.1", features = ["percent-encode", "secure"] }
fastwebsockets = { version = "0.7.1", features = ["upgrade"] }
flate2 = "1.0.28"
httparse = "1.8.0"
httpdate = "1.0.3"
hyper = { version = "1.2.0", features = ["full"] }
hyper-util = { version = "0.1.3", features = ["tokio"] }
mime_guess = "2.0.4"
multer = { version = "3.0.0", features = ["json"] }
percent-encoding = "2.3.0"
pin-project = "1.1.3"
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
regex = "1.9.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
serde_urlencoded = "0.7.1"
sha1 = "0.10.6"
tokio = { version = "1.28.1", features = ["rt-multi-thread"] }
tower-layer = "0.3.2"
tower-service = "0.3.2"

[dev-dependencies]
tokio = { version = "1.28.1", features = ["rt-multi-thread", "macros", "test-util", "parking_lot"] }
criterion = { version = "0.5.1", features = ["async_tokio"] }
tower-http = { version = "0.5.2", features = ["compression-gzip"] }

[[bench]]
name = "request_routing"
harness = false

